#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Koki Iwai
# SPDX-License-Identifier: BSD-3-Clause

import sys


def tonum(s):
    try:
        return int(line)
    except:
        return float(line)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
