#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Koki Iwai
# SPDX-License-Identifier: BSD-3-Clause

import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = []
tool = 2
co = 0

for inptline in sys.stdin:
    inptnum = int(inptline.strip())

    if inptnum == 1:
        ans.append(inptnum) 

    while inptnum > 1:
        while inptnum % tool == 0:
            ans.append(tool)
            inptnum = inptnum/tool
        tool += 1
        if inptnum < tool:
            break
print(ans)
